# Generated by Django 5.0.1 on 2024-01-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name': 'Likes par Article'},
        ),
    ]
